[build]
command = "next build && next export"
publish = "out"

# Redirect root to /login
[[redirects]]
  from = "/"
  to = "/login"
  status = 301

# Handle client-side routes (e.g., /dashboard)
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200